[package]
name = "pop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "2.0.0"

[dependencies.uuid]
version = "1.10.0"
features = ["v4", "v7", "fast-rng", "macro-diagnostics"]
